# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    # 缓存主项目依赖
    - name: Cache root node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-root-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-root-${{ matrix.node-version }}-
          ${{ runner.os }}-node-root-
    - run: npm install
    - run: npm run build --if-present
    - run: npm run vitest:run
    - run: npm test
    # https://github.com/marketplace/actions/vitest-coverage-report
    - name: 'Report Coverage'
      # if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v2
    - name: Generate markdown files
      run: npm run docs:build
    # 缓存 tsdoc 子目录依赖
    - name: Cache tsdoc node modules
      uses: actions/cache@v4
      with:
        path: tsdoc/node_modules
        key: ${{ runner.os }}-node-tsdoc-${{ matrix.node-version }}-${{ hashFiles('tsdoc/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-tsdoc-${{ matrix.node-version }}-
          ${{ runner.os }}-node-tsdoc-
    # tsdoc 是单独的文档项目，因为vuepress@1.X 与webpack@5.X 一起使用报错，所以单独抽离出来
    - name: Generate static html files
      working-directory: tsdoc
      run: npm install && npm run docs:build
